package hap.fruit.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.hand.hap.core.annotation.MultiLanguage;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@MultiLanguage
@Table(name = "fruit")
public class Fruit extends BaseDTO {
    @Id
    @GeneratedValue
    @Column
    private Long id;
    @Column
   @MultiLanguageField
    @Condition(operator = "LIKE")
    private String name;
    @Column
    private Long price;
    @Column
    @MultiLanguageField
    private String producingArea;
    //语言字段
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Transient
    private String lang;


    public void setId(Long id){
        this.id = id;
    }

    public Long getId(){
        return id;
    }

    public void setName(String name){
        this.name = name;
    }

    public String getName(){
        return name;
    }

    public void setPrice(Long price){
        this.price = price;
    }

    public Long getPrice(){
        return price;
    }

    public void setProducingArea(String producingArea){
        this.producingArea = producingArea;
    }

    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    public String getProducingArea(){

        return producingArea;
    }
}